system: 
  first_db: mysql
  mode: debug
  port: :9090
  url: http://127.0.0.1:9090
  max_check_count: 10
mysql:
  name: backend_service
  host: 127.0.0.1:3306
  username: root
  password: "@Aamother0120"
jwt:
  secret:  secretKeyIsHere
  issuer:  vueGinRefactor
  expire: 7200
log:
  level: debug
  filename: "server.log"
  max_size: 200
  max_age: 7
  max_backups: 10
